### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by 53N4** [Mmuurrmmuurr/RimWorld#1]
Hello! I made an [Spanish/SpanishLatin translation](https://privatebin.net/?620dc1c9c3828804#npctNRPOQPbcA+2vsPtt2JJD/zqQ31sy+pN/VloYUmc=), here I leave it if you want add it ^^

**Comment by Mmuurrmmuurr** [comment]
Hey thanks, I'll add it now!

**Comment by 53N4** [comment]
A pleasure! ^^ But... you only added it for the Latin version! It must be:
Languages\SpanishLatin\ *
Languages\Spanish\ *

**Comment by Mmuurrmmuurr** [comment]
Oh oops... haha thanks.
