### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by SolariusScorch** [Mmuurrmmuurr/RimWorld#3]
Hi,
I had no idea how to reach you, so I've decided to open an issue. I hope it's okay.
I made a Polish translation for your excellent Wall Light mod. If it's fine with you, please add it!
[WallLightPolishTranslation.zip](https://github.com/MurmurSix/RimWorld/files/4677699/WallLightPolishTranslation.zip)
Many thanks for your amazing work!
Solar

**Comment by Mmuurrmmuurr** [comment]
Hey thanks, I'll add it now.

**Comment by SolariusScorch** [comment]
Thank you! :)
